//
//  StyleKit.h
//  QuadMonitoring
//
//  Created by Stanislav Dymedyuk on 1/25/16.
//  Copyright (c) 2016 idistvi. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Drawing Methods
+ (void)drawBatteryWithBatteryLevel: (CGFloat)batteryLevel;
+ (void)drawTargetCanvasWithFrame: (CGRect)frame;

@end
